### create feature
POST http://localhost:8080/features
Content-Type: application/json

{
  "name": "feature 1",
  "description": "feature 1 설명"
}


### get feature
GET http://localhost:8080/features/1
Accept: application/json


### get feature list
GET http://localhost:8080/features?page=1&size=10
Accept: application/json


### update feature
PUT http://localhost:8080/features/1
Content-Type: application/json

{
  "name": "feature 1",
  "description": "feature 1 설명"
}


### delete feature
DELETE http://localhost:8080/features/1

###

