logging:
  level:
#    root: DEBUG
    org.springframework.web: TRACE

server:
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
